### ISSUE TITLE
Gulp not working with nodejs v10 (solved)

### ISSUE THREAD

**Issue by paulovieira** [cssninjaStudio/bulkit-public#12]
This issue is useful only for future reference (might be helpful for others). It can be closed.

@cssninjaStudio , feel free to create a link in the documentation to this issue

-----

I had problems using the gulp tasks provided with bulkit 2.2:

```bash
~/bulkit-2.2.0/kit-dashboard$ gulp build
gulp build[7106]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0x8daaa0 node::Abort() [gulp build]
 2: 0x8dab75  [gulp build]
 3: 0x90e2f7 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp build]
 4: 0xb5e71b  [gulp build]
 5: 0xb606b2 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [gulp build]
 6: 0x10b57a35be1d 
Aborted (core dumped)
~/bulkit-2.2.0/kit-dashboard$
```

The problem is related to some incompatibility between the version of nodejs being used, and the gulp-sass package in the original `package.json`.

The workaround was simple:

1) remove everything:
```
~/bulkit-2.2.0/kit-dashboard$rm -rf node_modules
~/bulkit-2.2.0/kit-dashboard$rm -rf package-lock.json
```

2) edit `package.json` and bump the version of gulp-sass from "2.x.x" to "3.0.0"

3) `npm install` again (might also be necessary to `npm rebuild`? not sure...)

**Comment by cssninjaStudio** [comment]
Hello, thanks for the workaround. You mean you solved the issue just by upgrading gulp-sass ?

**Comment by paulovieira** [comment]
That's right. It's just a matter of upgrading the `gulp-sass` package (to 3.0.0, or higher). That version of gulp-sass will also  install more recent versions of LibSass (and some other things, maybe), which solves the incompatibilities with recent versions of nodejs.

In fact, it might happen that 3.0.0 will also work with your current installation of nodejs (which I guess is 6, or maybe 4). If that's the case, you could also use 3.0.0 in your machine, and everyone would be happy.

**Comment by cssninjaStudio** [comment]
Indeed that’s a good fix although I need to switch to gulp 4 at some point. I also run several versions of node on my machine but this will help a lot. Thanks!

**Comment by theo-stocchetti** [comment]
Closed for inactivity, please reopen this ticket if you see a similar problem.
