### ISSUE TITLE
Bare Theme with no JS: Will integrate my JS

### ISSUE THREAD

**Issue by afidegnum** [cssninjaStudio/bulkit-public#13]
Hi, 

I would like to purchase Bulkit but while testing your previous your open source versions, I had hard time isolating the JS. 

I While coding and transpiling Js from [ELM](https://elm-lang.org/) I would like to have more control with custom elements to interact with. 

Do you have special discounts?

**Comment by theo-stocchetti** [comment]
Closed for inactivity, please reopen this ticket if this topic seems relevant.
