### ISSUE TITLE
Form on Agency Contact page is not working properly

### ISSUE THREAD

**Issue by Jacek-ja** [cssninjaStudio/bulkit-public#14]
[https://bulkitv2.cssninja.io/agency/agency-contact.html](https://bulkitv2.cssninja.io/agency/agency-contact.html)

Field without '\*' (_Company_) as required and with '\*' (_Message_) as not required??

![Screenshot_2019-04-30 Bulkit Contact](https://user-images.githubusercontent.com/46890649/56955742-8121cb80-6b42-11e9-931f-76deba916947.png)

When _Company_ field is made as not `required`... (**something is wrong!**)

![obraz](https://user-images.githubusercontent.com/46890649/56956771-613fd700-6b45-11e9-82af-6b0640883bca.png)

And there is something wrong with _Message_ `textarea` field...

![obraz](https://user-images.githubusercontent.com/46890649/57692942-5195b780-7648-11e9-819b-1bd513d8f139.png)

**Comment by cssninjaStudio** [comment]
Hello, this might be because some styles might be tied to the required attribute. Let me look at this to see if i can find something. Regarding the message input, what is exactly happening? the label overlaps the text when the input is unfocused ?

**Comment by Jacek-ja** [comment]
Yes, exactly.

**Comment by theo-stocchetti** [comment]
Nous avons mis à jour la documentation.

**Comment by theo-stocchetti** [comment]
Closed for inactivity, please reopen this ticket if you see a similar problem.
