### ISSUE TITLE
Gulp not working with Node 12.8.0 (MacOS Mojave)

### ISSUE THREAD

**Issue by mark5280** [cssninjaStudio/bulkit-public#15]
Hi - I purchased the Bulkit theme today and have been trying to get gulp operational.  Like others I'm getting the "AssertionError [ERR_ASSERTION]: Task function must be specified" error when using Node 12.8.  I've seen a few references to downgrade to Node 6 but the issues where this was mentioned were sometime in 2018. 

I've registered to access the Css Ninja forum to look at the how-to mentioned there in an attempt to resolve but just waiting to get my account activated.  

Thanks for any assistance you can provide so I can get up and running.

Mark

**Comment by cssninjaStudio** [comment]
Hi, unfortunately Nodejs v12 seems to have compatibility problems with gulp 3 combined to node-sass. The best solution would be to use NVM and downgrade your node version to v10 until we are able to switch to gulp 4. We didn't have any time available to dive in this conversion, so if you have any gulp expertise, maybe you could propose a PR to upgrade to gulp 4. If not, we will start thinking about upgrading it.

**Comment by theo-stocchetti** [comment]
Closed for inactivity, please reopen this ticket if you see a similar problem.
