### ISSUE TITLE
I can't get the theme to install

### ISSUE THREAD

**Issue by mariablomberg** [cssninjaStudio/bulkit-public#18]
Hi! 

Just downloaded your theme but can't get it to install. It thinks for a while and goes to twentysixteen  theme with an issue text of "Oops! That page can’t be found" . Upgraded my hosting package to make sure there was enough space, any advice?

All the best
Maria

Item Purchase Code:
c3561368-38b6-4134-921c-73c4cc0b8479

**Comment by mariablomberg** [comment]
If it doesn't work, I'm gonna ask for a refund

**Comment by cssninjaStudio** [comment]
Hello Maria,
Based on what you're saying, it seems you are trying to install Bulkit as if it was a WordPress theme, which is not and which is **clearly stated in the item description** on ThemeForest. Also, you should know that mistaken purchases are not supported by Envato customer refund policy.
https://themeforest.net/page/customer_refund_policy

Best.

**Comment by theo-stocchetti** [comment]
Closed for inactivity, please reopen this ticket if you see a similar problem.
